### ISSUE TITLE
config/packages/scheb_2fa.yaml add new configuration error

### ISSUE THREAD

**Issue by yasincetintas** [erkens/2fa-text#2]
Hi. I installed this package but, send error message " Unrecognized option "two_factor_text" under "scheb_two_factor". Available options are "email", "ip_whitelist", "ip_whitelist_provider", "model_manager_name", "persister", "security_tokens", "totp", "two_factor_c  
  ondition", "two_factor_token_factory".  "  after "bin/console c:c"

**Comment by erkens** [comment]
I think that you have the "two_factor_text" element in your yaml file under the "scheb_two_factor" element, but it must be on the root.

Can you provide your config file if that didn't fix it?

**Comment by yasincetintas** [comment]
Thank you for the support. My issue hasn't been resolved yet. According to your instructions, the definition I made inside the config/packages/scheb_2fa.yaml file is as follows:
`
scheb_two_factor:
    email:
        enabled: true
        sender_email: crm.accounts@next4biz.net
        sender_name: Two Factor
        mailer: custom_auth_code_mailer
        digits: 6                      # Number of digits in authentication code
#        template: security/login.html.twig   # Template used to render the authentication form
    two_factor_text:
        enabled: true
        auth_code_sender: App\Security\SMSSender\DefaultAndUserProviderSender
        digits: 6
        text: 'To login, use this code: %s'
#        template: '@SchebTwoFactor/Authentication/form.html.twig'
`

I think you are saying it should be like the following in your root directory.

`
# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/5.x/configuration.html
scheb_two_factor:
    email:
        enabled: true
        sender_email: crm.accounts@next4biz.net
        sender_name: Two Factor
        mailer: custom_auth_code_mailer
        digits: 6                      # Number of digits in authentication code
#        template: security/login.html.twig   # Template used to render the authentication form
two_factor_text:
    enabled: true
    auth_code_sender: App\Security\SMSSender\DefaultAndUserProviderSender
    digits: 6
    text: 'To login, use this code: %s'
#        template: '@SchebTwoFactor/Authentication/form.html.twig'
`

**Comment by yasincetintas** [comment]
This usage worked.

```
scheb_two_factor:
    email:
        enabled: true
        sender_email: crm.accounts@aa.net
        sender_name: Two Factor
        mailer: custom_auth_code_mailer
        digits: 6
two_factor_text:
    enabled: true
    auth_code_sender: App\Security\SMSSender\DefaultAndUserProviderSender
    digits: 6
    text: 'To login, use this code: %s'
```

But it is necessary to implement the TwoFactorTextInterface on the user entity. 
It's not present in the README, I wanted to mention it additionally. It would be good if you add it.
Thanks.
